crud/config/routes.rb
Crud::Application.routes.draw do
  
  match "contatos/lista" => "contatos#lista", :as => :lista_contatos
  match "contatos/novo" => "contatos#novo",  :via => :get,
                                             :as => :novo_contato
  match "contatos/novo" => "contatos#salva", :via => :post

  match "contatos/exclui/:id" => "contatos#exclui", 
                            :as => :exclui_contato

  resources :compromissos

end

crud/app/models/compromisso.rb
class Compromisso < ActiveRecord::Base
  attr_accessible :data, :descricao, :hora
end

crud/app/models/contato.rb
class Contato < ActiveRecord::Base
  attr_accessible :email, :nome, :telefone
end

crud/app/controllers/compromissos_controller.rb
# encoding: UTF-8
class CompromissosController < ApplicationController

    def index
        @compromissos = Compromisso.all #(:order => 'data desc')
    end

    def new
        @compromisso = Compromisso.new
    end

    def create
        logger.info 'Salvando o compromisso ...'
        @compromisso = Compromisso.new params[:compromisso]
        @compromisso.save
        # flash[:notice] = 'Compromisso salvo'
        redirect_to compromissos_path, :notice => 'Compromisso salvo'
    end

    def edit
        @compromisso = Compromisso.find params[:id]        
    end

    def update
        @compromisso = Compromisso.find params[:id]
        @compromisso.update_attributes params[:compromisso]
        redirect_to compromissos_path, :notice => 'Compromisso salvo'
    end

    def destroy
        @compromisso = Compromisso.find params[:id]
        @compromisso.destroy
        redirect_to compromissos_path, :notice => 'Compromisso excluido'
    end


end

crud/app/controllers/contatos_controller.rb
class ContatosController < ApplicationController
  def novo
  end

  def lista
    @contatos = Contato.all    
  end

  def exclui
    c = Contato.find_by_id(params[:id])
    if c
        c.delete
        flash[:sucesso] = "Contato excluido com sucesso"
    else
        flash[:erro] = "Contato nao existe"
    end
    redirect_to :lista_contatos
  end

  def salva

    Contato.create :nome => params[:nome],
                   :telefone => params[:telefone],
                   :email => params[:email]

    # notice, warning, error
    flash[:sucesso] = "Contato salvo com sucesso"

    redirect_to :lista_contatos
  end

end

crud/app/helpers/compromissos_helper.rb
module CompromissosHelper
end

crud/app/helpers/contatos_helper.rb
module ContatosHelper
end

crud/app/views/compromissos/edit.html.erb
<h1>Editar Compromisso</h1>

<%= form_for @compromisso do |f| %>

    <%= f.label :descricao, 'Descrição:' %>
    <%= f.text_field :descricao %>

    <%= f.label :data, 'Data:' %>
    <%= f.date_select :data %>

    <%= f.label :hora, 'Hora:' %>
    <%= f.time_select :hora %>

    <%= f.submit 'Salvar' %>

<% end %>

crud/app/views/compromissos/index.html.erb
<h1>Lista de Compromissos</h1>

<% if flash[:notice] %>
    <div class="notice">
        <%= flash[:notice] %>
    </div>
<% end %>

<div>
    <%= link_to 'Novo Compromisso', new_compromisso_path %>
</div>

<table>
    <tr>
        <th>Descrição</th>
        <th></th>
    </tr>

    <% for c in @compromissos %>

    <tr>
        <td>
            <%= c.descricao %>
        </td>
        <td>
            <%= link_to 'Editar', edit_compromisso_path(c) %>
            <%= link_to 'Excluir', c, :method => :delete %>
        </td>
    </tr>

    <% end %>
</table>

crud/app/views/compromissos/new.html.erb
<h1>Novo Compromisso</h1>

<%= form_for @compromisso do |f| %>

    <%= f.label :descricao, 'Descrição:' %>
    <%= f.text_field :descricao %>

    <%= f.label :data, 'Data:' %>
    <%= f.date_select :data %>

    <%= f.label :hora, 'Hora:' %>
    <%= f.time_select :hora %>

    <%= f.submit 'Salvar' %>

<% end %>

crud/app/views/contatos/lista.html.erb
<h1>Lista de Contatos</h1>

<% if flash[:sucesso] %>
    <div class="sucesso">
        <%= flash[:sucesso] %>
    </div>
<% end %>

<% if flash[:erro] %>
    <div class="erro">
        <%= flash[:erro] %>
    </div>
<% end %>

<div>
    <%= link_to "Novo Contato", novo_contato_path %>
</div>

<table>
    <thead>
        <tr><th>Nome</th><th>Telefone</th><th></th></tr>
    </thead>
    <tbody>
    <% for c in @contatos %>
        <tr>
            <td><%= c.nome %></td>
            <td><%= c.telefone %></td>
            <td><%= link_to "Excluir", exclui_contato_path(c.id) %></td>
        </tr>
    <% end %>
    </tbody>
</table>

crud/app/views/contatos/novo.html.erb
<h1>Novo Contato</h1>

<form method="post">

    <label for="nome">Nome:</label>
    <input type="text" id="nome" name="nome"
           size="50" maxlength="50" />

    <label for="telefone">Telefone:</label>
    <input type="text" id="telefone" name="telefone"
           size="20" maxlength="20" />

    <label for="email">E-mail:</label>
    <input type="email" id="email" name="email"
           size="50" maxlength="50" />

    <input type="submit" value="Salvar"/>

</form>

crud/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Crud</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<div id="content">
    <%= yield %>
</div>

</body>
</html>