facefrase/config/routes.rb
Facefrase::Application.routes.draw do
  resources :usuarios

  match "login" => "login#index", :via => :get,
        :as => :login

  match "login" => "login#login", :via => :post

  match "logout" => "login#logout"

  match "frase/nova" => "frase#nova",
        :via => :get, :as => :nova_frase

  match "frase/nova" => "frase#posta",
        :via => :post

  match "frase/like/:id" => "frase#like",
        :via => :post, :as => :like

  root :to => 'home#index'
  

end

facefrase/app/models/frase.rb
class Frase < ActiveRecord::Base
  attr_accessible :autor, :dislikes, :likes, :texto
end

facefrase/app/models/usuario.rb
class Usuario < ActiveRecord::Base
  attr_accessible :email, :nome, :senha, :salt
end

facefrase/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

facefrase/app/controllers/frase_controller.rb
# encoding: UTF-8
class FraseController < ApplicationController
  before_filter :verifica_antenticacao

  def nova
  end

  def posta
    # salvar a frase
  end

  def like
    @frase = Frase.find(params[:id])
    @frase.likes = 0 unless @frase.likes
    @frase.likes = @frase.likes + 1
    @frase.save
    render :template => "home/_likes", :layout => false
  end

  private
  def verifica_antenticacao
    if session[:usuario].nil?
        flash[:notice] = 'Precisa logar'
        redirect_to login_path
    end
  end
end

facefrase/app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @ultimas_5_frases = Frase.order('created_at DESC').limit(5)
  end
end

facefrase/app/controllers/login_controller.rb
# encoding: UTF-8

require 'openssl'

class LoginController < ApplicationController
  def index
  end


  def logout
    session[:usuario] = nil
    redirect_to root_path
  end

  def login
    u = Usuario.find_by_email params[:email]

    sha = OpenSSL::Digest::SHA256.new

    if u.nil?
        flash[:notice] = 'Usuário não existe'
        render :action => :index
    elsif u.senha != sha.hexdigest(u.salt + params[:senha])
        flash[:notice] = 'Senha não confere'
        render :action => :index
    else
        session[:usuario] = u.nome
        redirect_to root_path
    end
  end
end

facefrase/app/controllers/usuarios_controller.rb
# encoding: UTF-8

require 'openssl'
require 'securerandom'

class UsuariosController < ApplicationController
  # GET /usuarios
  # GET /usuarios.json
  def index
    @usuarios = Usuario.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @usuarios }
    end
  end

  # GET /usuarios/1
  # GET /usuarios/1.json
  def show
    @usuario = Usuario.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @usuario }
    end
  end

  # GET /usuarios/new
  # GET /usuarios/new.json
  def new
    @usuario = Usuario.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @usuario }
    end
  end

  # GET /usuarios/1/edit
  def edit
    @usuario = Usuario.find(params[:id])
  end

  # POST /usuarios
  # POST /usuarios.json
  def create
    @usuario = Usuario.new(params[:usuario])

    sha = OpenSSL::Digest::SHA256.new

    salt = SecureRandom.hex

    hash = sha.hexdigest(salt + @usuario.senha)

    logger.info(hash)

    @usuario.senha = hash
    @usuario.salt  = salt

    respond_to do |format|
      if @usuario.save
        format.html { redirect_to @usuario, notice: 'Usuario was successfully created.' }
        format.json { render json: @usuario, status: :created, location: @usuario }
      else
        format.html { render action: "new" }
        format.json { render json: @usuario.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /usuarios/1
  # PUT /usuarios/1.json
  def update
    @usuario = Usuario.find(params[:id])

    respond_to do |format|
      if @usuario.update_attributes(params[:usuario])
        format.html { redirect_to @usuario, notice: 'Usuario was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @usuario.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /usuarios/1
  # DELETE /usuarios/1.json
  def destroy
    @usuario = Usuario.find(params[:id])
    @usuario.destroy

    respond_to do |format|
      format.html { redirect_to usuarios_url }
      format.json { head :no_content }
    end
  end
end

facefrase/app/helpers/application_helper.rb
module ApplicationHelper
end

facefrase/app/helpers/frase_helper.rb
module FraseHelper
end

facefrase/app/helpers/home_helper.rb
module HomeHelper
end

facefrase/app/helpers/login_helper.rb
module LoginHelper
end

facefrase/app/helpers/usuarios_helper.rb
module UsuariosHelper
end

facefrase/app/views/frase/nova.html.erb
<% @titulo = 'Nova frase' %>

<form method="post">
<label>Texto:</label>
<br>
<input type="text" name="texto" size="77" maxlength="77">
<br>
<label>Autor:</label>
<br>
<input type="text" name="autor" size="22" maxlength="22">
<br>
<input type="submit" value="Postar">
</form>

facefrase/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Facefrase</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<div style="float:right">
<%= "Logado como #{session[:usuario]}" unless session[:usuario].nil? %>
<%= link_to 'Sair', logout_path unless session[:usuario].nil? %>

<%= 'Tu não estás logado' if session[:usuario].nil? %>
<%= link_to 'Login', login_path if session[:usuario].nil? %>
</div>

<h1>FaceFrase</h1>

<h2><%= @titulo %></h2>

<strong><%= flash[:notice] %></strong>

<%= yield %>

<div id="rodape">
    <%= yield :rodape %>
</div>

</body>
</html>

facefrase/app/views/usuarios/_form.html.erb
<%= form_for(@usuario) do |f| %>
  <% if @usuario.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@usuario.errors.count, "error") %> prohibited this usuario from being saved:</h2>

      <ul>
      <% @usuario.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :nome %><br />
    <%= f.text_field :nome %>
  </div>
  <div class="field">
    <%= f.label :senha %><br />
    <%= f.password_field :senha %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

facefrase/app/views/usuarios/edit.html.erb
<h1>Editing usuario</h1>

<%= render 'form' %>

<%= link_to 'Show', @usuario %> |
<%= link_to 'Back', usuarios_path %>

facefrase/app/views/usuarios/index.html.erb
<h1>Listing usuarios</h1>

<table>
  <tr>
    <th>Email</th>
    <th>Nome</th>
    <th>Senha</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @usuarios.each do |usuario| %>
  <tr>
    <td><%= usuario.email %></td>
    <td><%= usuario.nome %></td>
    <td><%= usuario.senha %></td>
    <td><%= link_to 'Show', usuario %></td>
    <td><%= link_to 'Edit', edit_usuario_path(usuario) %></td>
    <td><%= link_to 'Destroy', usuario, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Usuario', new_usuario_path %>

facefrase/app/views/usuarios/new.html.erb
<h1>New usuario</h1>

<%= render 'form' %>

<%= link_to 'Back', usuarios_path %>

facefrase/app/views/usuarios/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Email:</b>
  <%= @usuario.email %>
</p>

<p>
  <b>Nome:</b>
  <%= @usuario.nome %>
</p>

<p>
  <b>Senha:</b>
  <%= @usuario.senha %>
</p>


<%= link_to 'Edit', edit_usuario_path(@usuario) %> |
<%= link_to 'Back', usuarios_path %>